[package]
name = "kitc"
version = "0.1.0"
edition = "2024"

[dependencies]
kitlang = { path = "../kitlang" }
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
which = "8.0.0"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
log = "0.4.29"
