[package]
name = "kitc"
version = "0.1.0"
edition = "2024"

[dependencies]
kitlang = { path = "../kitlang" }
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
which = "8.0.0"
